
version: '3'

services:

    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ./mongo/data:/data/db
        networks:
            - node-net

    node:
        build: ../
        volumes:
            - ../:/var/www/node
        ports:
            - 3000:3000
        networks:
            - node-net
        depends_on:
            - mongo

networks:
    node-net:
        driver: bridge
